### ISSUE TITLE
实测 ubuntu-latest 已集成 php，可以删除步骤中安装 php 的流程

### ISSUE THREAD

**Issue by bruceCzK** [peng4740/Tieba_Github-Actions#6]
亲测直接运行脚本就可以

```
name: Run it on action

on:
  workflow_dispatch: # 可以手动触发 action
  schedule:
    - cron: 15 8,20 * * * # 定时触发
jobs:
  run-it:
    runs-on: ubuntu-latest
    name: Tieba Checkin
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Run
        run: |
          if [ '${{ secrets.BDUSS }}' != '' ]; then sed -i "s/xxxxx/${{ secrets.BDUSS }}/" tieba.php; fi
          php tieba.php
```

![image](https://user-images.githubusercontent.com/8399711/94518793-b7dea280-025c-11eb-99e1-5ded555f8dbc.png)

![image](https://user-images.githubusercontent.com/8399711/94519936-017bbd00-025e-11eb-8598-b09e4eb9bebc.png)

https://github.com/bruceCzK/Tieba_Github-Actions
